export const COUNTRY_KEY = 'neptune_country'
export const COUNTRY_MANUAL_KEY = 'neptune_country_manual'
export const COUNTRY_CHANGED_EVENT = 'neptune-country-changed'

export interface CountryEntry {
  countryCode: string
  countryName: string
  currencyCode: string
  currencySymbol: string
}

export const COUNTRY_LIST: CountryEntry[] = [
  { countryCode: 'AF', countryName: 'Afghanistan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AX', countryName: 'Åland Islands', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AL', countryName: 'Albania', currencyCode: 'ALL', currencySymbol: 'L' },
  { countryCode: 'DZ', countryName: 'Algeria', currencyCode: 'DZD', currencySymbol: 'د.ج' },
  { countryCode: 'AD', countryName: 'Andorra', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AO', countryName: 'Angola', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AI', countryName: 'Anguilla', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'AG', countryName: 'Antigua & Barbuda', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'AR', countryName: 'Argentina', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AM', countryName: 'Armenia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AW', countryName: 'Aruba', currencyCode: 'AWG', currencySymbol: 'ƒ' },
  { countryCode: 'AC', countryName: 'Ascension Island', currencyCode: 'SHP', currencySymbol: '£' },
  { countryCode: 'AU', countryName: 'Australia', currencyCode: 'AUD', currencySymbol: '$' },
  { countryCode: 'AT', countryName: 'Austria', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AZ', countryName: 'Azerbaijan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BS', countryName: 'Bahamas', currencyCode: 'BSD', currencySymbol: '$' },
  { countryCode: 'BH', countryName: 'Bahrain', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BD', countryName: 'Bangladesh', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BB', countryName: 'Barbados', currencyCode: 'BBD', currencySymbol: '$' },
  { countryCode: 'BY', countryName: 'Belarus', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BE', countryName: 'Belgium', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BZ', countryName: 'Belize', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BJ', countryName: 'Benin', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BM', countryName: 'Bermuda', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'BT', countryName: 'Bhutan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BO', countryName: 'Bolivia', currencyCode: 'BOB', currencySymbol: 'Bs.' },
  { countryCode: 'BA', countryName: 'Bosnia & Herzegovina', currencyCode: 'BAM', currencySymbol: 'КМ' },
  { countryCode: 'BW', countryName: 'Botswana', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BR', countryName: 'Brazil', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'IO', countryName: 'British Indian Ocean Territory', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'VG', countryName: 'British Virgin Islands', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'BN', countryName: 'Brunei', currencyCode: 'BND', currencySymbol: '$' },
  { countryCode: 'BG', countryName: 'Bulgaria', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BF', countryName: 'Burkina Faso', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'BI', countryName: 'Burundi', currencyCode: 'BIF', currencySymbol: 'Fr' },
  { countryCode: 'KH', countryName: 'Cambodia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'CM', countryName: 'Cameroon', currencyCode: 'XAF', currencySymbol: 'CFA' },
  { countryCode: 'CA', countryName: 'Canada', currencyCode: 'CAD', currencySymbol: '$' },
  { countryCode: 'CV', countryName: 'Cape Verde', currencyCode: 'CVE', currencySymbol: '$' },
  { countryCode: 'BQ', countryName: 'Caribbean Netherlands', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'KY', countryName: 'Cayman Islands', currencyCode: 'KYD', currencySymbol: '$' },
  { countryCode: 'CF', countryName: 'Central African Republic', currencyCode: 'XAF', currencySymbol: 'CFA' },
  { countryCode: 'TD', countryName: 'Chad', currencyCode: 'XAF', currencySymbol: 'CFA' },
  { countryCode: 'CL', countryName: 'Chile', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'CN', countryName: 'China', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'CX', countryName: 'Christmas Island', currencyCode: 'AUD', currencySymbol: '$' },
  { countryCode: 'CC', countryName: 'Cocos (Keeling) Islands', currencyCode: 'AUD', currencySymbol: '$' },
  { countryCode: 'CO', countryName: 'Colombia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'KM', countryName: 'Comoros', currencyCode: 'KMF', currencySymbol: 'Fr' },
  { countryCode: 'CG', countryName: 'Congo - Brazzaville', currencyCode: 'XAF', currencySymbol: 'CFA' },
  { countryCode: 'CD', countryName: 'Congo - Kinshasa', currencyCode: 'CDF', currencySymbol: 'Fr' },
  { countryCode: 'CK', countryName: 'Cook Islands', currencyCode: 'NZD', currencySymbol: '$' },
  { countryCode: 'CR', countryName: 'Costa Rica', currencyCode: 'CRC', currencySymbol: '₡' },
  { countryCode: 'CI', countryName: "Côte d'Ivoire", currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'HR', countryName: 'Croatia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'CW', countryName: 'Curaçao', currencyCode: 'ANG', currencySymbol: 'ƒ' },
  { countryCode: 'CY', countryName: 'Cyprus', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'CZ', countryName: 'Czechia', currencyCode: 'CZK', currencySymbol: 'Kč' },
  { countryCode: 'DK', countryName: 'Denmark', currencyCode: 'DKK', currencySymbol: 'kr.' },
  { countryCode: 'DJ', countryName: 'Djibouti', currencyCode: 'DJF', currencySymbol: 'Fdj' },
  { countryCode: 'DM', countryName: 'Dominica', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'DO', countryName: 'Dominican Republic', currencyCode: 'DOP', currencySymbol: '$' },
  { countryCode: 'EC', countryName: 'Ecuador', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'EG', countryName: 'Egypt', currencyCode: 'EGP', currencySymbol: 'ج.م' },
  { countryCode: 'SV', countryName: 'El Salvador', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'GQ', countryName: 'Equatorial Guinea', currencyCode: 'XAF', currencySymbol: 'CFA' },
  { countryCode: 'ER', countryName: 'Eritrea', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'EE', countryName: 'Estonia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SZ', countryName: 'Eswatini', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'ET', countryName: 'Ethiopia', currencyCode: 'ETB', currencySymbol: 'Br' },
  { countryCode: 'FK', countryName: 'Falkland Islands', currencyCode: 'FKP', currencySymbol: '£' },
  { countryCode: 'FO', countryName: 'Faroe Islands', currencyCode: 'DKK', currencySymbol: 'kr.' },
  { countryCode: 'FJ', countryName: 'Fiji', currencyCode: 'FJD', currencySymbol: '$' },
  { countryCode: 'FI', countryName: 'Finland', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'FR', countryName: 'France', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GF', countryName: 'French Guiana', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'PF', countryName: 'French Polynesia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'TF', countryName: 'French Southern Territories', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GA', countryName: 'Gabon', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GM', countryName: 'Gambia', currencyCode: 'GMD', currencySymbol: 'D' },
  { countryCode: 'GE', countryName: 'Georgia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'DE', countryName: 'Germany', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GH', countryName: 'Ghana', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GI', countryName: 'Gibraltar', currencyCode: 'GBP', currencySymbol: '£' },
  { countryCode: 'GR', countryName: 'Greece', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GL', countryName: 'Greenland', currencyCode: 'DKK', currencySymbol: 'kr.' },
  { countryCode: 'GD', countryName: 'Grenada', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'GP', countryName: 'Guadeloupe', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GT', countryName: 'Guatemala', currencyCode: 'GTQ', currencySymbol: 'Q' },
  { countryCode: 'GG', countryName: 'Guernsey', currencyCode: 'GBP', currencySymbol: '£' },
  { countryCode: 'GN', countryName: 'Guinea', currencyCode: 'GNF', currencySymbol: 'Fr' },
  { countryCode: 'GW', countryName: 'Guinea-Bissau', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GY', countryName: 'Guyana', currencyCode: 'GYD', currencySymbol: '$' },
  { countryCode: 'HT', countryName: 'Haiti', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'HN', countryName: 'Honduras', currencyCode: 'HNL', currencySymbol: 'L' },
  { countryCode: 'HK', countryName: 'Hong Kong SAR', currencyCode: 'HKD', currencySymbol: '$' },
  { countryCode: 'HU', countryName: 'Hungary', currencyCode: 'HUF', currencySymbol: 'Ft' },
  { countryCode: 'IS', countryName: 'Iceland', currencyCode: 'ISK', currencySymbol: 'kr' },
  { countryCode: 'IN', countryName: 'India', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'ID', countryName: 'Indonesia', currencyCode: 'IDR', currencySymbol: 'Rp' },
  { countryCode: 'IQ', countryName: 'Iraq', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'IE', countryName: 'Ireland', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'IM', countryName: 'Isle of Man', currencyCode: 'GBP', currencySymbol: '£' },
  { countryCode: 'IL', countryName: 'Israel', currencyCode: 'ILS', currencySymbol: '₪' },
  { countryCode: 'IT', countryName: 'Italy', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'JM', countryName: 'Jamaica', currencyCode: 'JMD', currencySymbol: '$' },
  { countryCode: 'JP', countryName: 'Japan', currencyCode: 'JPY', currencySymbol: '¥' },
  { countryCode: 'JE', countryName: 'Jersey', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'JO', countryName: 'Jordan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'KZ', countryName: 'Kazakhstan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'KE', countryName: 'Kenya', currencyCode: 'KES', currencySymbol: 'KSh' },
  { countryCode: 'KI', countryName: 'Kiribati', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'XK', countryName: 'Kosovo', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'KW', countryName: 'Kuwait', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'KG', countryName: 'Kyrgyzstan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LA', countryName: 'Laos', currencyCode: 'LAK', currencySymbol: '₭' },
  { countryCode: 'LV', countryName: 'Latvia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LB', countryName: 'Lebanon', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LS', countryName: 'Lesotho', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LR', countryName: 'Liberia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LY', countryName: 'Libya', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LI', countryName: 'Liechtenstein', currencyCode: 'CHF', currencySymbol: 'CHF' },
  { countryCode: 'LT', countryName: 'Lithuania', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LU', countryName: 'Luxembourg', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MO', countryName: 'Macao SAR', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MG', countryName: 'Madagascar', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MW', countryName: 'Malawi', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MY', countryName: 'Malaysia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MV', countryName: 'Maldives', currencyCode: 'MVR', currencySymbol: 'MVR' },
  { countryCode: 'ML', countryName: 'Mali', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MT', countryName: 'Malta', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MQ', countryName: 'Martinique', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MR', countryName: 'Mauritania', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MU', countryName: 'Mauritius', currencyCode: 'MUR', currencySymbol: '₨' },
  { countryCode: 'YT', countryName: 'Mayotte', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MX', countryName: 'Mexico', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MD', countryName: 'Moldova', currencyCode: 'MDL', currencySymbol: 'L' },
  { countryCode: 'MC', countryName: 'Monaco', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MN', countryName: 'Mongolia', currencyCode: 'MNT', currencySymbol: '₮' },
  { countryCode: 'ME', countryName: 'Montenegro', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MS', countryName: 'Montserrat', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'MA', countryName: 'Morocco', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MZ', countryName: 'Mozambique', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'MM', countryName: 'Myanmar (Burma)', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'NA', countryName: 'Namibia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'NR', countryName: 'Nauru', currencyCode: 'AUD', currencySymbol: '$' },
  { countryCode: 'NP', countryName: 'Nepal', currencyCode: 'NPR', currencySymbol: 'Rs.' },
  { countryCode: 'NL', countryName: 'Netherlands', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'NC', countryName: 'New Caledonia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'NZ', countryName: 'New Zealand', currencyCode: 'NZD', currencySymbol: '$' },
  { countryCode: 'NI', countryName: 'Nicaragua', currencyCode: 'NIO', currencySymbol: 'C$' },
  { countryCode: 'NE', countryName: 'Niger', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'NG', countryName: 'Nigeria', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'NU', countryName: 'Niue', currencyCode: 'NZD', currencySymbol: '$' },
  { countryCode: 'NF', countryName: 'Norfolk Island', currencyCode: 'AUD', currencySymbol: '$' },
  { countryCode: 'MK', countryName: 'North Macedonia', currencyCode: 'MKD', currencySymbol: 'ден' },
  { countryCode: 'NO', countryName: 'Norway', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'OM', countryName: 'Oman', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'PK', countryName: 'Pakistan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'PS', countryName: 'Palestinian Territories', currencyCode: 'ILS', currencySymbol: '₪' },
  { countryCode: 'PA', countryName: 'Panama', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'PG', countryName: 'Papua New Guinea', currencyCode: 'PGK', currencySymbol: 'K' },
  { countryCode: 'PY', countryName: 'Paraguay', currencyCode: 'PYG', currencySymbol: '₲' },
  { countryCode: 'PE', countryName: 'Peru', currencyCode: 'PEN', currencySymbol: 'S/' },
  { countryCode: 'PH', countryName: 'Philippines', currencyCode: 'PHP', currencySymbol: '₱' },
  { countryCode: 'PN', countryName: 'Pitcairn Islands', currencyCode: 'NZD', currencySymbol: '$' },
  { countryCode: 'PL', countryName: 'Poland', currencyCode: 'PLN', currencySymbol: 'zł' },
  { countryCode: 'PT', countryName: 'Portugal', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'QA', countryName: 'Qatar', currencyCode: 'QAR', currencySymbol: 'ر.ق' },
  { countryCode: 'RE', countryName: 'Réunion', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'RO', countryName: 'Romania', currencyCode: 'RON', currencySymbol: 'Lei' },
  { countryCode: 'RU', countryName: 'Russia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'RW', countryName: 'Rwanda', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'WS', countryName: 'Samoa', currencyCode: 'WST', currencySymbol: 'T' },
  { countryCode: 'SM', countryName: 'San Marino', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'ST', countryName: 'São Tomé & Príncipe', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SA', countryName: 'Saudi Arabia', currencyCode: 'SAR', currencySymbol: 'ر.س' },
  { countryCode: 'SN', countryName: 'Senegal', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'RS', countryName: 'Serbia', currencyCode: 'RSD', currencySymbol: 'РСД' },
  { countryCode: 'SC', countryName: 'Seychelles', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SL', countryName: 'Sierra Leone', currencyCode: 'SLL', currencySymbol: 'Le' },
  { countryCode: 'SG', countryName: 'Singapore', currencyCode: 'SGD', currencySymbol: '$' },
  { countryCode: 'SX', countryName: 'Sint Maarten', currencyCode: 'ANG', currencySymbol: 'ƒ' },
  { countryCode: 'SK', countryName: 'Slovakia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SI', countryName: 'Slovenia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SB', countryName: 'Solomon Islands', currencyCode: 'SBD', currencySymbol: '$' },
  { countryCode: 'SO', countryName: 'Somalia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'ZA', countryName: 'South Africa', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'GS', countryName: 'South Georgia & South Sandwich Islands', currencyCode: 'GBP', currencySymbol: '£' },
  { countryCode: 'KR', countryName: 'South Korea', currencyCode: 'KRW', currencySymbol: '₩' },
  { countryCode: 'SS', countryName: 'South Sudan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'ES', countryName: 'Spain', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'LK', countryName: 'Sri Lanka', currencyCode: 'LKR', currencySymbol: '₨' },
  { countryCode: 'BL', countryName: 'St. Barthélemy', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SH', countryName: 'St. Helena', currencyCode: 'SHP', currencySymbol: '£' },
  { countryCode: 'KN', countryName: 'St. Kitts & Nevis', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'LC', countryName: 'St. Lucia', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'MF', countryName: 'St. Martin', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'PM', countryName: 'St. Pierre & Miquelon', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'VC', countryName: 'St. Vincent & Grenadines', currencyCode: 'XCD', currencySymbol: '$' },
  { countryCode: 'SD', countryName: 'Sudan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SR', countryName: 'Suriname', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SJ', countryName: 'Svalbard & Jan Mayen', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'SE', countryName: 'Sweden', currencyCode: 'SEK', currencySymbol: 'kr' },
  { countryCode: 'CH', countryName: 'Switzerland', currencyCode: 'CHF', currencySymbol: 'CHF' },
  { countryCode: 'TW', countryName: 'Taiwan', currencyCode: 'TWD', currencySymbol: '$' },
  { countryCode: 'TJ', countryName: 'Tajikistan', currencyCode: 'TJS', currencySymbol: 'ЅМ' },
  { countryCode: 'TZ', countryName: 'Tanzania', currencyCode: 'TZS', currencySymbol: 'Sh' },
  { countryCode: 'TH', countryName: 'Thailand', currencyCode: 'THB', currencySymbol: '฿' },
  { countryCode: 'TL', countryName: 'Timor-Leste', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'TG', countryName: 'Togo', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'TK', countryName: 'Tokelau', currencyCode: 'NZD', currencySymbol: '$' },
  { countryCode: 'TO', countryName: 'Tonga', currencyCode: 'TOP', currencySymbol: 'T$' },
  { countryCode: 'TT', countryName: 'Trinidad & Tobago', currencyCode: 'TTD', currencySymbol: '$' },
  { countryCode: 'TA', countryName: 'Tristan da Cunha', currencyCode: 'GBP', currencySymbol: '£' },
  { countryCode: 'TN', countryName: 'Tunisia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'TR', countryName: 'Türkiye', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'TM', countryName: 'Turkmenistan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'TC', countryName: 'Turks & Caicos Islands', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'TV', countryName: 'Tuvalu', currencyCode: 'AUD', currencySymbol: '$' },
  { countryCode: 'UM', countryName: 'U.S. Outlying Islands', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'UG', countryName: 'Uganda', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'UA', countryName: 'Ukraine', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'AE', countryName: 'United Arab Emirates', currencyCode: 'AED', currencySymbol: 'د.إ' },
  { countryCode: 'GB', countryName: 'United Kingdom', currencyCode: 'GBP', currencySymbol: '£' },
  { countryCode: 'US', countryName: 'United States', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'UY', countryName: 'Uruguay', currencyCode: 'UYU', currencySymbol: '$U' },
  { countryCode: 'UZ', countryName: 'Uzbekistan', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'VU', countryName: 'Vanuatu', currencyCode: 'VUV', currencySymbol: 'Vt' },
  { countryCode: 'VA', countryName: 'Vatican City', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'VE', countryName: 'Venezuela', currencyCode: 'USD', currencySymbol: '$' },
  { countryCode: 'VN', countryName: 'Vietnam', currencyCode: 'VND', currencySymbol: '₫' },
  { countryCode: 'WF', countryName: 'Wallis & Futuna', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'EH', countryName: 'Western Sahara', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'YE', countryName: 'Yemen', currencyCode: 'YER', currencySymbol: '﷼' },
  { countryCode: 'ZM', countryName: 'Zambia', currencyCode: 'EUR', currencySymbol: '€' },
  { countryCode: 'ZW', countryName: 'Zimbabwe', currencyCode: 'USD', currencySymbol: '$' },
]

const COUNTRY_MAP = new Map(COUNTRY_LIST.map((c) => [c.countryCode, c]))

export function getCountryEntry(countryCode: string): CountryEntry | undefined {
  return COUNTRY_MAP.get(countryCode)
}

export function getStoredCountry(): string | null {
  if (typeof window === 'undefined') return null
  return localStorage.getItem(COUNTRY_KEY)
}

export function setStoredCountry(countryCode: string): void {
  if (typeof window === 'undefined') return
  localStorage.setItem(COUNTRY_KEY, countryCode)
}

/** True only when the user has explicitly picked a country from the selector. */
export function isCountryManuallySet(): boolean {
  if (typeof window === 'undefined') return false
  return localStorage.getItem(COUNTRY_MANUAL_KEY) === 'true'
}

export function markCountryAsManual(): void {
  if (typeof window === 'undefined') return
  localStorage.setItem(COUNTRY_MANUAL_KEY, 'true')
}

export function dispatchCountryChanged(countryCode: string): void {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(
      new CustomEvent(COUNTRY_CHANGED_EVENT, { detail: { countryCode } })
    )
  }
}
